### ISSUE TITLE
"Force full syncrhonization" only runs after restart

### ISSUE THREAD

**Issue by sualfred** [Montellese/mediaimporter.emby#36] opened 2020-06-13 08:02 UTC
"Force full synchronization" should start as soon as OK was hit.
It also makes sense to add a "Repair synchronization" next to "Synchronize" in the context menu.

Btw:
Syncronise or Syncronize. BR and US English is used together in the strings.po

**Comment by Montellese** [comment] 2020-06-13 18:55
I actually wanted to do this as well but it's not so easy.

First of all I'd have to add a way for python add-ons to trigger a synchronization. That's not difficult.

The problem is that if you make any changes in the settings dialog and then click the "Force full synchronization" button those changed settings will not have been saved yet so if there would be a way to force a synchronization it would be executed with the old settings which is certainly not what users would expect.

Settings are only saved when closing the dialog using the "OK" button. If you exit with the "Cancel" button or by pressing ESC the changes will be lost.

**Comment by Montellese** [comment] 2021-03-11 14:57
This should be more or less solved in combination with https://github.com/Montellese/xbmc/issues/80. If any of the settings change (this includes pressing the `Force full synchronization` button) the user is asked whether he wants to synchronize the provider / import. It's not the most intuitive approach but at least the user doesn't have to know / remember to manually start the synchronization process.

With the next test builds I'll adjust the add-on to show a dialog informing the user that (s)he has to save the settings before the forced full synchronization takes place.

Is that good enough?

**Closed as completed** 2021-05-20 06:49 UTC
Labels: Type: Improvement, Component: Synchronization
