### ISSUE TITLE
Real Time Events from Server not reported in Kodi

### ISSUE THREAD

**Issue by Long-Man** [Montellese/mediaimporter.emby#6] opened 2020-01-04 04:35 UTC
Real time events (Web Socket Events) like marking something watched on the server did not show up in Kodi until I did a re-sync.

**Comment by Montellese** [comment] 2020-01-04 08:44
This was working once but I haven't explicitly tested it in a while. Do you see a message in the logs that Kodi succesfully connected to your Emby server?

There might also still be issues with the Python 3 migration. I haven't tested the websocket part yet...

**Comment by Long-Man** [comment] 2020-01-04 14:10
The web socket error was reported in the Emby forum. I  tested it and confirmed it. I played a cople of movies on both servers and marked one as watched on the Jellyfin server. None were reflected in Kodi. I am not sure if you need the server logs too.

https://drive.google.com/file/d/1IDb3g6WFSpW4hbX-ZDskFhaxe6AnR5rO/view?usp=sharing

**Comment by Montellese** [comment] 2020-01-04 23:46
I can confirm that no websocket messages are received by the add-on. I'll have to figure out where this was broken. We had to make some changes to the websocket client for the Python 3 migration...

**Comment by Montellese** [comment] 2020-01-07 22:31
I just tested it with the latest `py3` branch (with the external `script.module.websocket_client` and it's working fine again.

**Comment by Long-Man** [comment] 2020-01-08 00:43
I can confirm this. Kodi is updating with play status live when online. 

Is the plugin pulling script.module.websocket_client from the repo for you, i had to install it manually

**Comment by Montellese** [comment] 2020-01-08 12:13
TBH I'm not yet familiar with the custom repository stuff. One issue certainly is that the versions of the mediaimporter add-ons in the repository are still Python 2 only and don't require the external script.module.websocket_client yet.

I'll soon merge the py3 branch into master and then we can update the repository and see if it works properly.

Unfortunately I've fallen sick so I'm only on my phone for now...

**Comment by Long-Man** [comment] 2020-01-08 14:56
Sorry to hear that. Take care of yourself. That's the most important thing. The other things can be sorted afterwards.

**Comment by Montellese** [comment] 2020-01-08 21:29
This should be fixed in `master` now since I merged the `py3` branch.

**Closed as completed by Montellese** 2020-01-08 21:29 UTC
Labels: Type: Bug, Component: Observation
